swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

#GET POUR ACCOUNT
  /account/{account_id}: 
    get:
      tags:
        - Account Module
      summary: Get Account Details
      description: Retrieve detailed information about a specific account.
      parameters:
        - in: path  
          name: account_id  
          description: Unique identifier of the account to retrieve.
          required: true
          type: string  
       
      produces:
        - application/json
      responses:
        '200':
          description: Account details retrieved successfully
          schema:
            $ref: '#/definitions/AccountResponse'
        '400':
          description: Invalid request or missing parameters
        '404':
          description: Account not found
        '500':
          description: Internal Server Error

#GET POUR TOUTES LES TRANSACTIONS
  /account/{account_id}/transactions/: 
    get:
      tags:
        - Transactions Module
      summary: Get All transactions
      description: Retrieve information about transactions from a specific account.
      parameters:
        - in: path  
          name: account_id  
          description: Account ID
          required: true
          type: string  
       
      produces:
        - application/json
      responses:
        '200':
          description: Transactions details retrieved successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

#POST POUR UNE TRANSACTION
  /account/{account_id}/transactions/{transaction_id}: 
    post:
      tags:
        - Transactions Module
      summary: Post a transaction
      description: API to create a new transaction from a specific account
      parameters:
        - in: path  
          name: account_id  
          description: Account ID
          required: true
          type: string  
        - in: path  
          name: transaction_id  
          description: Transaction ID
          required: true
          type: string  
        - in: body
          name: body
          description: Transactions Payload
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction created successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
#GET POUR UNE TRANSACTION
    get:
      tags:
        - Transactions Module
      summary: Get Transaction
      description: API to retrieve details of a specific transaction from an account
      parameters:
        - in: path  
          name: account_id  
          description: Account ID
          required: true
          type: string  
        - in: path  
          name: transaction_id  
          description: Transaction ID
          required: true
          type: string  
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details retrieved successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
#PUT POUR UNE TRANSACTION
    put:
      tags:
        - Transactions Module
      summary: Modify a Transaction
      description: API to modify details of a specific transaction from an account
      parameters:
        - in: path  
          name: account_id  
          description: Account ID
          required: true
          type: string  
        - in: path  
          name: transaction_id  
          description: Transaction ID
          required: true
          type: string  
        - in: body
          name: body
          description: Transactions Payload
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction modified Successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

#DELETE POUR UNE TRANSACTION
    delete:
      tags:
        - Transactions Module
      summary: Delete a Transaction 
      description: API to delete a specific transaction from an account
      parameters:
        - in: path  
          name: account_id  
          description: Account ID
          required: true
          type: string  
        - in: path  
          name: transaction_id  
          description: Transaction ID
          required: true
          type: string  
      produces:
        - application/json
      responses:
        '200':
          description: Transaction deleted Successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string



  Account:
    properties:
      category:
        type: string
        description: account category
      number:
        type: string    
        description: account number
      status:
        type: string    
        description: account status
  AccountResponse:
    type: object 
    properties:  
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          account:
            type: string
          number:
            type: string
          status:
            type: string
  Transaction:
    type: object
    properties:
      date:
        type: string
        format: date
        description: transaction date
      description:
        type: string
        description: transaction description
      amount:
        type: number
        format: double
        description: transaction amount

  TransactionsResponse:
    type: object  
    properties:  
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          $ref: '#/definitions/Transaction'
